USE relatorios;
SET SQL_SAFE_UPDATES = 0;
SET GLOBAL local_infile=1; # enables the LOCAL data import

# general querys for loading data from CSV´S
LOAD DATA LOCAL INFILE 'C:/data/Relatorio_cadop teste 3.csv'
INTO TABLE infos_op  CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 3 LINES;

LOAD DATA LOCAL INFILE 'C:/data/2020/1T2020.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2020/2T2020.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2020/3T2020.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2020/4T2020.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2021/1T2021.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2021/2T2021.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2021/3T2021.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'C:/data/2021/4T2021.csv'
INTO TABLE financeiro_op CHARACTER SET LATIN1 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

# changing the date pattern to fit the SQL standards
UPDATE infos_op SET data_registro =
    DATE_FORMAT(STR_TO_DATE(data_registro, '%d/%m/%Y'), '%Y-%m-%d') 
WHERE data_registro LIKE '__/__/____';

UPDATE financeiro_op SET data_financeiro =
    DATE_FORMAT(STR_TO_DATE(data_financeiro, '%d/%m/%Y'), '%Y-%m-%d') 
WHERE data_financeiro LIKE '__/__/____';